name: cellpose
channels:
  - conda-forge
dependencies:
  - ipykernel
  - python=3.11.14
  - pip:
    - ImageIO==2.37.2
    - Jinja2==3.1.6
    - MarkupSafe==3.0.3
    - PIMS==0.7
    - PyYAML==6.0.3
    - bokeh==3.8.1
    - cellpose==4.0.7
    - click==8.3.1
    - cloudpickle==3.1.2
    - contourpy==1.3.3
    - dask==2025.11.0
    - dask-image==2025.11.0
    - dask-jobqueue==0.9.0
    - distributed==2025.11.0
    - donfig==0.8.1.post1
    - fastremap==1.17.7
    - filelock==3.20.0
    - fill_voids==2.1.1
    - fsspec==2025.10.0
    - google-crc32c==1.7.1
    - imagecodecs==2025.11.11
    - locket==1.0.0
    - mpmath==1.3.0
    - msgpack==1.1.2
    - narwhals==2.12.0
    - natsort==8.4.0
    - networkx==3.5
    - numcodecs==0.16.5
    - numpy==2.2.6
    - nvidia-cublas-cu12==12.8.4.1
    - nvidia-cuda-cupti-cu12==12.8.90
    - nvidia-cuda-nvrtc-cu12==12.8.93
    - nvidia-cuda-runtime-cu12==12.8.90
    - nvidia-cudnn-cu12==9.10.2.21
    - nvidia-cufft-cu12==11.3.3.83
    - nvidia-cufile-cu12==1.13.1.3
    - nvidia-curand-cu12==10.3.9.90
    - nvidia-cusolver-cu12==11.7.3.90
    - nvidia-cusparse-cu12==12.5.8.93
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-nccl-cu12==2.27.5
    - nvidia-nvjitlink-cu12==12.8.93
    - nvidia-nvshmem-cu12==3.3.20
    - nvidia-nvtx-cu12==12.8.90
    - opencv-python-headless==4.12.0.88
    - pandas==2.3.3
    - partd==1.4.2
    - pillow==12.0.0
    - pyarrow==22.0.0
    - pytz==2025.2
    - roifile==2025.5.10
    - scipy==1.16.3
    - segment-anything==1.0
    - slicerator==1.1.0
    - sortedcontainers==2.4.0
    - sympy==1.14.0
    - tblib==3.2.2
    - tifffile==2025.10.16
    - toolz==1.1.0
    - torch==2.9.1
    - torchvision==0.24.1
    - tqdm==4.67.1
    - triton==3.5.1
    - tzdata==2025.2
    - urllib3==2.5.0
    - xyzservices==2025.10.0
    - zarr==3.1.5
    - zict==3.0.0
