name: bigstream
channels:
  - conda-forge
dependencies:
  - ipykernel
  - python=3.11
  - zarr==2.18.7
  - pip:
    - ClusterWrap==1.0.3
    - ImageIO==2.37.2
    - Jinja2==3.1.6
    - MarkupSafe==3.0.3
    - PyYAML==6.0.3
    - annotated-types==0.7.0
    - bigstream==5.0.2
    - bokeh==3.8.1
    - click==8.3.1
    - cloudpickle==3.1.2
    - contourpy==1.3.3
    - dask==2025.11.0
    - dask-jobqueue==0.9.0
    - distributed==2025.11.0
    - donfig==0.8.1.post1
    - fishspot==0.5.0
    - fsspec==2025.12.0
    - google-crc32c==1.7.1
    - h5py==3.15.1
    - joblib==1.5.2
    - lazy_loader==0.4
    - locket==1.0.0
    - morphsnakes==2.0.1
    - narwhals==2.13.0
    - networkx==3.6
    - numpy==1.26.4
    - ome-zarr-models==0.1.10
    - opencv-python==4.11.0.86
    - pandas==2.3.3
    - partd==1.4.2
    - pillow==12.0.0
    - pydantic==2.11.4
    - pydantic-zarr==0.9.0
    - pydantic_core==2.33.2
    - pynrrd==1.1.3
    - pytz==2025.2
    - scikit-image==0.25.2
    - scikit-learn==1.8.0
    - scipy==1.16.3
    - simpleitk==2.5.3
    - sortedcontainers==2.4.0
    - tblib==3.2.2
    - threadpoolctl==3.6.0
    - tifffile==2025.10.16
    - toolz==1.1.0
    - typing-inspection==0.4.2
    - tzdata==2025.2
    - urllib3==2.5.0
    - xyzservices==2025.11.0
    - zict==3.0.0